### ISSUE TITLE
Hello, I'm stuck here when I'm doing image retrieval. I can't detect the result

### ISSUE THREAD

**Issue by yueliangshuile** [souravbhatnagar/image_retrieval_backend#4]
![捕获](https://user-images.githubusercontent.com/66929684/115153387-393a3d00-a0a8-11eb-9b9c-dbc0e69d851c.PNG)

**Comment by souravbhatnagar** [comment]
Soon I'll be updating the repository with fully functional code.

**Comment by yueliangshuile** [comment]
Thanks.Can you update it this week?------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月19日(星期一) 晚上7:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [souravbhatnagar/image_retrieval_backend] Hello, I&#39;m stuck here when I&#39;m doing image retrieval. I can&#39;t detect the result (#4)

**Comment by yueliangshuile** [comment]
> 很快，我将使用功能齐全的代码更新存储库。

Thanks.Can you update it this week?

**Comment by souravbhatnagar** [comment]
The code is up to date now. :)
